name: Build gir2swift and build SwiftGtk

# Dependencies of Glib package
env:
  UBUNTU_APT: ${{ 'libpango1.0-dev libglib2.0-dev libgdk-pixbuf2.0-dev gobject-introspection libcairo2-dev libatk1.0-dev glib-networking libgtk-3-dev libgirepository1.0-dev' }}

on:
  pull_request:
    branches: [ master ]
jobs:

  # Ubuntu 20.04 tasks
  build-ubuntu-20_04-swift-latest:
    runs-on: ubuntu-20.04
    steps:
      - name: Print Swift version to confirm
        run: swift --version
      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout gir2swift
        uses: actions/checkout@v2
        with:
          path: gir2swift
      - name: Checkout testing repo
        uses: actions/checkout@v2
        with:
          repository: rhx/SwiftGtk
          path: swiftGtk

      - name: Build current gir2swift
        run: |
          cd gir2swift
          ./build.sh
          cd ..
      - name: Export executable
        run: |
          echo "GIR2SWIFT_PATH=${PWD}/gir2swift/.build/release/" >> $GITHUB_ENV
          echo "${PWD}/gir2swift/.build/release/" >> $GITHUB_PATH
      - name: Test export success
        run: gir2swift

      - name: Build gtk
        run: |
          cd swiftGtk
          ./build.sh
          cd ..
      
      - name: Remove unneeded files and archive artifacts
        run: | 
          cd gir2swift
          swift package clean
          rm -rf .build/repositories
          cd ../swiftGtk
          swift package clean
          rm -rf .build/repositories
          cd ..
          zip -r build.zip gir2swift swiftGtk
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-20.04-5.3
          path: build.zip
          retention-days: 1
